global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: monitoring
    static_configs:
      - targets: ['localhost:9090']
  - job_name: ec2_exporter_node
    ec2_sd_configs:
      - port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
  - job_name: ec2_exporter_main_service
    ec2_sd_configs:
      - port: 9101
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance